package domain

/*
 * Copyright (c) 2019,201 Norwegian University of Science and Technology
 */

const (
	ContactInfoTypeAddressHome       = "address_home"
	ContactInfoTypeAddressWork       = "address_work"
	ContactInfoTypeAddressSemester   = "address_semester"
	ContactInfoTypeEmailPrivate      = "email_personal"
	ContactInfoTypeEmailWork         = "email_work"
	ContactInfoTypePhoneHome         = "phone_personal"
	ContactInfoTypePhoneMobile       = "phone_mobile"
	ContactInfoTypePhoneSemster      = "phone_semester"
	ContactInfoTypePhoneWork         = "phone_work"
	ContactInfoTypePhoneOther        = "phone_other"
	ContactInfoTypeURL               = "url"
	ContactInfoTypeCVURL             = "cv_url"
	ContactInfoTypeTwitterID         = "twitter_url"
	ContactInfoTypeFacebookID        = "facebook_url"
	ContactInfoTypeGoogleID          = "google_url"
	ContactInfoTypeLinkedinID        = "linkedin_url"
	ContactInfoTypeLink1             = "link_1"
	ContactInfoTypeLink1Text         = "link_1_text"
	ContactInfoTypeLink2             = "link_2"
	ContactInfoTypeLink2Text         = "link_2_text"
	ContactInfoTypeBygning           = "bygning"
	ContactInfoTypeRom               = "rom"
	ContactInfoTypeBilReg            = "bilreg"
	ContactInfoTypeSIPAddress        = "sip_address"
	ContactInfoTypePictureURL        = "pictureUrl"
	ContactInfoTypeProfileImageURL   = "profile_image_url"
	ContactInfoTypeProfileAaddress   = "profile_address"
	ContactInfoTypeCristinProfileURL = "cristin_profile_url"
	ContactInfoTypeUserProfileURL    = "cristin_profile_url"

	// Extension types:
	ExtensionTypeOrgResponsible    = "responsible"
	ExtensionTypeOrgAdmin          = "reglementsted"
	ExtensionTypeRomIBygning       = "rom_i_bygning"
	ExtensionTypeOrgWork           = "work"
	ExtensionTypePrimaryOrg        = "primary_org_unit"
	ExtensionTypeOrgVisibility     = "org_unit_visible"
	ExtensionTypeOtherOrgRef       = "other_org_unit_ref"
	ExtensionTypePostitionName     = "position_name"
	ExtensionTypePostitionCode     = "position_code"
	ExtensionTypePostitionCategory = "position_category"
	ExtensionTypeLonnstrinnA       = "lonnstrinn_a"
	ExtensionTypeLonnstrinnB       = "lonnstrinn_b"
	ExtensionTypeTjenesteforhold   = "tjenesteforhold"
	ExtensionTypeLonnskode         = "lonnskode"
	ExtensionTypePositionPerCent   = "position_percent"
	ExtensionTypeEmploymentFrom    = "employment_from"
	ExtensionTypePositionFrom      = "position_from"
	ExtensionTypePositionTo        = "position_to"
	ExtensionTypeSalaryFrom        = "salary_from"
	ExtensionTypeSalaryTo          = "salary_to"
	ExtensionTypeRegion            = "region"
	ExtensionTypeSite              = "site"
	ExtensionTypeBuilding          = "building"
	ExtensionTypeFloor             = "floor"
	ExtensionTypeBDMDim1           = "dim1"
	ExtensionTypeBDMDim2           = "dim2"
	ExtensionTypeLicense           = "license"
	ExtensionTypeForerkort         = "førerkort"
	ExtensionTypeAffiliationSource = "bas_affiliation_source"

	// ID types:
	IdTypeMeta               = "systemUrn"
	IdTypeOrgID              = "ouid"
	IdTypeCostcenter         = "costcenter"
	IdTypeStudyUnit          = "study_unit"
	IdTypeNSD                = "nsd"
	IdTypeAnsattnr           = "ansattnr"
	IdTypeNIN                = "nin"
	IdTypeFSLopenr           = "fslopenr"
	IdTypeStudentnummer      = "studentnr"
	IdTypePrimaryEmailAdress = "email"
	IdTypeUsername           = "username"
	// IdentityTypeFeideID is the entity-type for feide-identity
	IdTypeFeideID                   = "feideid"
	IdTypeBASID                     = "basid"
	IdTypeMaconomyID                = "maconomyid"
	IdTypeLMSLopenr                 = "lmslopenr"
	IdTypePersonBBKeyname           = "bbuserid"
	IdTypeTopdeskPersUUID           = "personuuid"
	IdTypeTopdeskBranchUUID         = "branchuuid"
	IdTypeTopdeskDepartmentUUID     = "departmentuuid"
	IdTypeTopdeskRoleUUID           = "roleuuid"
	IdTypeUndenhetKeyname           = "undenhetkode"
	IdTypeUndenhetBBExternalKeyname = "eksternundenhetkode"
	IdTypeUndenhetBBKeyname         = "bbcourseid"
	IdTypeUndaktivitetKeyname       = "undaktivitetkode"
	IdTypeEmneKeyname               = "emnekode"
	IdTypeInfoTerminEmneKeyname     = "infoTerminEmne"
	IdTypeArsterminkode             = "arsterminkode"
	IdTypeKullKeyname               = "kullkode"
	IdTypeKullKlasseKeyname         = "kullklassekode"
	IdTypeStudieretningKeyname      = "studieretningkode"
	IdTypeCampusKeyname             = "campuskode"
	IdTypeTPUndAktivitetKeyname     = "tpaktivitetkode"
	IdTypeTPUndaktHendelseKeyname   = "tpundakthendelsekode"
	IdTypeEmnekombinasjonKeyname    = "emnekombinasjonkode"
	IdTypeStudieprogramKeyname      = "studieprogramkode"
	IdTypeTimeplanKeyname           = "timeplankode"
	// IdentityTypeBilregEmail is entity-type for e-mail address
	IdTypeBilregEmail                = "bilregemail"
	IdTypeTerminKeyname              = "terminkode"
	IdTypeVurderingKeyname           = "vurderingkode"
	IdTypeRomKeyname                 = "romkode"
	IdTypeRomIBygning                = "rom_i_bygning"
	IdTypeBygningKeyname             = "bygningkode"
	IdTypeSyllabusRomkode            = "syllabusromkode"
	IdTypeIDCPersonID                = "personid"
	IdTypeAccessCard                 = "accesscard"
	IdTypeAccessCardLayout           = "cardlayout"
	IdTypeMyfareID                   = "mifareid"
	IdTypeCardID                     = "cardid"
	IdTypeCardNo                     = "cardno"
	IdTypeRoletypeKeyname            = "rolletype"
	IdTypeOUHierarchyID              = "hierarchyId"
	IdTypeCountryID                  = "landnummer"
	IdTypeCcountyID                  = "fylkesnummer"
	IdTypeMunicipality_ID            = "kommunenummer"
	IdTypeLydiaID                    = "lydiaid"
	IdTypeRegionnavn                 = "regionnavn"
	IdTypeAanalysis                  = "analysis"
	IdTypeProject                    = "project"
	IdTypeCostType                   = "costtype"
	IdTypeFinanacingProgram          = "project"
	IdTypeFinanacingCategory         = "project"
	IdTypePprojectGroup              = "projectgroup"
	IdTypeDFOAnsattID                = "dfo_ansatt_id"
	IdTypeDFOOrgID                   = "dfo_org_id"
	IdTypeDFOStillingID              = "dfo_stilling_id"
	IdTypeDFOStillingskode           = "dfo_stillingskode"
	IdTypeDFOYrkeskode               = "dfo_yrkeskode"
	IdTypeDFOEkstrastilling          = "dfo_ekstrastilling"
	IdTypeDFODellonnsprosent         = "dfo_dellonnsprosent"
	IdTypeDFOStillingsKatID          = "dfo_stillingskatid"
	IdTypeDFOStillingstittelL        = "dfo_stillingstittel"
	IdTypeDFOStillingsnavn           = "dfo_stillingsnavn"
	IdTypeDFOMedarbeiderGruppe       = "dfo_mg"
	IdTypeDFOMedarbeiderUndergruppe  = "dfo_mug"
	IdTypePassnummer                 = "passnummer"
	IdTypeDFOSocialSecurityNumber    = "dfo_social_security_number"
	IdTypeDFOTaxIdentificationNumber = "dfo_tax_identification_number"
	IdTypeDFOVatIdentificationNumber = "dfo_vat_identification_number"
	IdTypeGregPersonID               = "greg_person_id"

	// Role types
	RoleTypeSchedule              = "schedule"
	RoleTypeExam                  = "exam"
	RoleTypeStaff                 = "staff"
	RoleTypeStaffname             = "staffname"
	RoleTypeResource              = "resource"
	RoleTypeExtraStaff            = "extraStaff"
	RoleTypeIntranet              = "intranet"
	RoleTypeLIS                   = "lis"
	RoleTypeChildOf               = "childOf"
	RoleTypeAnalysis              = "analysis"
	RoleTypeProject               = "project"
	RoleTypeProjectGroup          = "projectgroup"
	RoleTypeCostType              = "costtype"
	RoleTypeClearingProject       = "avregningsprosjekt"
	RoleTypeCampusRegion          = "campusregion"
	RoleTypeTerminPeriod          = "terminperiode"
	RoleTypeHeadBranch            = "headbranch"
	RoleTypeBranch                = "branch"
	RoleTypeDepartment            = "department"
	RoleTypeTopdesk               = "topdeskrole"
	RoleTypeBASExpiredCleanupDate = "cleanup_date"
	RoleTypeBASExpiredExpireDate  = "expire_date"
	RoleTypeBDMPerson             = "bdmperson"
	RoleTypeStilling              = "stilling"
	RoleTypeTilleggsstilling      = "tilleggsstilling"
	RoleTypeMedArbeiderGruppe     = "medarbeidergruppe"

	// TODO Should be fetched from configuration!!!
	InstitutionCode = "194"

	// Name types:
	NameTypeDisplayname  = "displayname"
	NameTypeFirstname    = "first name"
	NameTypeLastname     = "last name"
	NameTypeTitle        = "title"
	NameTypeTitleEnglish = "titleEnglish"
	NameTypeUsername     = "username"
	NameTypeFullname     = "fullname"
	NameTypeShortName    = "shortname"

	// Language codes:
	LanguageCodeNorwegian = "nob"
	LanguageCodeEnglish   = "eng"
	LanguageCodeNNO       = "nno"
	// Sami language (Northern Sami)
	LanguageCodeSME = "sme"

	// Semester-names
	SemesterNameSpringNorwegian = "VÅR"
	SemesterNameSummerNorwegian = "SOM"
	SemesterNameAutumnNorwegian = "HØST"

	// Organization relation types:
	OrgRelationTypeAffiliated     = "affiliated"
	OrgRelationTypeEmployee       = "employee"
	OrgRelationTypeStudent        = "student"
	OrgRelationTypeStemmerettsted = "stemmerettsted"
	OrgRelationTypeUndervisning   = "undervisning"

	SourceSystemUrnMeta              = "urn:meta"
	SourceSystemUrnBASPerson         = "urn:bas/person"
	SourceSystemUrnBAS2Person        = "urn:bas2/person"
	SourceSystemUrnBASExpired        = "urn:bas/expired"
	SourceSystemUrnFSFagperson       = "urn:fs/fagperson"
	SourceSystemUrnFSStedref         = "urn:fs/stedref"
	SourceSystemUrnFSStudent         = "urn:fs/student"
	SourceSystemUrnFSEmne            = "urn:fs/emne"
	SourceSystemUrnFSStudieprogram   = "urn:fs/studieprogram"
	SourceSystemUrnFSTermin          = "urn:fs/termin"
	SourceSystemUrnFSVurdering       = "urn:fs/vurdering"
	SourceSystemUrnFSRom             = "urn:fs/rom"
	SourceSystemUrnFSBygning         = "urn:fs/bygning"
	SourceSystemUrnFSUndenhet        = "urn:fs/undenhet"
	SourceSystemUrnFSUndaktivitet    = "urn:fs/undaktivitet"
	SourceSystemUrnFSAPIUndaktivitet = "urn:fsapi/undaktivitet"
	SourceSystemUrnFSAPITermin       = "urn:fsapi/termin"
	SourceSystemUrnFSKUll            = "urn:fs/kull"
	SourceSystemUrnFSCampus          = "urn:fs/campus"
	SourceSystemUrnFSAPICampus       = "urn:fsapi/campus"
	SourceSystemUrnBaswareIP         = "urn:baswareip/bdmperson"

	// TODO: Decide if there should be one FS source system urn!!!
	SourceSystemUrnFS                       = "urn:fs"
	SourceSystemUrnUserProfileServicePerson = "urn:userprofileservice/person"
	SourceSystemUrnUPSPerson                = "urn:ups/person"
	SourceSystemUrnOrg                      = "urn:orgreg/org"
	SourceSystemUrnOrg2                     = "urn:orgreg2/org"
	SourceSystemUrnOrg2B                    = "urn:orgreg2b/org"
	SourceSystemUrnOrg3                     = "urn:orgreg3/org"
	SourceSystemUrnOrgMeisterOU             = "urn:orgmeister/org"
	SourceSystemUrnOrgMeisterHierarchy      = "urn:orgmeister/hierarchy"
	// SourceSystemUrnBilregFeidePerson is the source-system for cars registered on feide-identity
	SourceSystemUrnBilregFeidePerson = "urn:bilreg/feideperson"
	// SourceSystemUrnBilregEpostPerson is the source-system for cars registered on e-mail address
	SourceSystemUrnBilregEpostPerson      = "urn:bilreg/epostperson"
	SourceSystemUrnTimeplanRom            = "urn:tp/rom"
	SourceSystemUrnTimeplanCourseActivity = "urn:tp/activity"
	SourceSystemUrnTimeplanAktivitet      = "urn:tp/aktivitet"
	SourceSystemUrnIDC                    = "urn:idc/autorisasjon"
	SourceSystemUrnTIA                    = "urn:tia"
	SourceSystemUrnUserPprofileService    = "urn:userprofileservice"
	SourceSystemUrnTjenesteforhold        = "urn:core/tjenesteforhold"
	SourceSystemUrnBBCourse               = "urn:bb/course"
	SourceSystemUrnBBPerson               = "urn:bb/person"
	SourceSystemUrnADTelefon              = "urn:ad/telefon"
	SourceSystemUrnLydia                  = "urn:lydia"
	SourceSystemUrnOFAnalysis             = "urn:of/analysis"
	SourceSystemUrnOFProject              = "urn:of/project"
	SourceSystemUrnOFCostcenter           = "urn:of/org"
	SourceSystemUrnTopdeskPerson          = "urn:topdesk/person"
	SourceSystemUrnTopdeskBranch          = "urn:topdesk/branch"
	SourceSystemUrnDFOPerson              = "urn:dfo/person"
	SourceSystemUrnDFOOrganisasjon        = "urn:dfo/org"
	SourceSystemUrnDFOTiaPerson           = "urn:dfo/tiaperson"

	// Status types:
	StatusTypeAtiv                = "aktiv"
	StatusTypeBBAktiv             = "bbAktiv"
	StatusTypeStudentStatus       = "studentstatkode"
	StatusTypeBetalingOK          = "betalingOk"
	StatusTypePermisjon           = "permisjon"
	StatusTypeRegistreringOK      = "registreringOk"
	StatusTypeExternalVisibility  = "externalVisibility"
	StatusTypeIniternalVisibility = "internalVisibility"
	StatusTypeAaccountAactivated  = "accountActivated"
	StatusTypePersonQuarantined   = "personQuarantined"
	StatusTypeReservePublish      = "reservePublish"
	StatusTypePhoneMobileHide     = "hidePhoneMobile"
	StatusTypePhoneOtherHide      = "hidePhoneOther"
	StatusTypePhoneNTNUHide       = "hidePhoneNTNU"

	StatusPolicyVersionID    = "policyVersionId"
	StatusPolicyAcceptDate   = "policyAcceptedDate"
	StatusIKTRulesVersionID  = "iktRulesVersionId"
	StatusIKTRulesAcceptDate = "iktRulesAcceptedDate"

	StatusTypeTillatNettpublisering = "nettpublisering"
	StatusTypeUseUerAddesAddress    = "useUserAddedAddress"
	StatusTypeReservertDistribusjon = "reservert_mot_lms_eksportering"
	StatusTypeDead                  = "død"
	StatusTypeUsePicture            = "status_bruk_bilde"
	StatusTypeTuition               = "semRegBetalt"
	StatusTypeFagperson             = "fagpersonstatus"
	StatusTypeDoNotShowProfile      = "doNotShowProfile"
	StatusTypeTopdeskPersArchived   = "personarchived"
	StatusTypeReservePrivMobile     = "reservePrivMobile"
	StatusTypeDFOLederFlagg         = "dfo_lederflagg"

	// IdentityTypeRoleTypeKeyname is the key-name for role-type
	IdentityTypeRoleTypeKeyname = "rolletype"
)
